name: dental_clinic
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.10.5+9
  path_provider: ^2.1.2
  path: ^1.8.3
  permission_handler: ^11.1.0
  cupertino_icons: ^1.0.6
  shared_preferences: ^2.4.0
  http: ^1.3.0
  proste_bezier_curve: ^2.0.2
  custom_clippers: ^2.0.0
  pinput: ^5.0.1
  provider: ^6.1.2
  intl: ^0.20.2
  dio: ^5.8.0+1
  image_picker: ^1.0.4
  flutter_colorpicker: ^1.1.0
  file_picker: ^9.0.0
  screenshot: ^3.0.0
  audioplayers: ^6.2.0
  record: ^6.1.2
  math_expressions: ^2.6.0
  just_audio: ^0.9.46
  flutter_resizable_container: ^4.0.1
  image: ^4.5.4
  http_parser: ^4.1.2
  share_plus: ^10.1.4
  vector_math: ^2.1.4
  tutorial_coach_mark: ^1.3.0
  showcaseview: ^4.0.1
  animated_text_kit: ^4.2.3
  collection: ^1.19.1
  font_awesome_flutter: ^10.8.0
  record_linux: ^1.2.1
  rename: ^3.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.14.4
  
flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/DentiX_app_icon.png"
  
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/DentiX_app_icon.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/images/DentiX_app_icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/DentiX_app_icon.png"
flutter:
  uses-material-design: true

  assets:
    - assets/images/     
    - assets/images/back_teeth.png
    
     # - assets/images/line_selection.jpeg
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Neuton
      fonts:
        - asset: assets\fonts\Neuton-Regular.ttf
        # - asset: fonts/Schyler-Italic.ttf
        #   style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
